# ----------------------------------------------------------------------
# BUILD GDAY BINARY
# ----------------------------------------------------------------------
FROM debian:stretch as gday-binary

# Some variables that can be used to set control the docker build
ARG MODEL_VERSION=git

# install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gcc \
       git \
       make \
    && rm -rf /var/lib/apt/lists/*

# download, and make gday
WORKDIR /src
RUN git -c http.sslVerify=false clone https://github.com/mdekauwe/GDAY.git\
    && cd GDAY/src \
    && make \

########################################################################

# ----------------------------------------------------------------------
# BUILD PECAN FOR MODEL
# ----------------------------------------------------------------------
FROM pecan/executor:latest

# ----------------------------------------------------------------------
# INSTALL MODEL SPECIFIC PIECES
# ----------------------------------------------------------------------

# INSTALL PEcAn.ED2
#COPY models/gday /src/gday/
#RUN Rscript --vanilla -e  "devtools::install_local('/src/gday'); q(status=as.integer(!'PEcAn.GDAY' %in% installed.packages()))" 

# ----------------------------------------------------------------------
# SETUP FOR SPECIFIC MODEL
# ----------------------------------------------------------------------

# Some variables that can be used to set control the docker build
ARG MODEL_VERSION=git

# variables to store in docker image
ENV APPLICATION="./job.sh" \
    MODEL_TYPE="" \
    MODEL_VERSION="${MODEL_VERSION}"

ENV RABBITMQ_QUEUE="${MODEL_TYPE}_${MODEL_VERSION}"

# COPY model binary
COPY --from=model-binary /src/GDAY/ED/build/ed_2.1-opt /usr/local/bin/ed2.${MODEL_VERSION}
